---
dist: xenial
language: python
python: 3.6
env:
  matrix:
    - MOLECULE_DISTRO: debian10

install:
  - pip3 install -r requirements.txt
  - ansible --version
  - molecule --version
script:
  - molecule create
  - molecule prepare
  - molecule test
