---
#####################################################################
# T-Pot - Abort if run as tpot, root or on unsupported distribution #
#####################################################################

# - name: Check if running as root (All)
#   assert:
#     that: ansible_user_id != 'root'
#     fail_msg: "T-Pot playbook should not be run as root."
#     success_msg: "Running as user: {{ ansible_user_id }}."

- name: Check if running as tpot (All)
  ansible.builtin.assert:
    that: ansible_facts['user_id'] != 'tpot'
    fail_msg: "Reserved username `tpot` detected."
    success_msg: "Running as user: {{ ansible_facts['user_id'] }}."

- name: Check if supported distribution (All)
  ansible.builtin.assert:
    that: ansible_facts['distribution'] in tpot_supported_distributions
    fail_msg: "T-Pot is not supported on this platform: {{ ansible_facts['distribution'] }}."
    success_msg: "T-Pot will now install on {{ ansible_facts['distribution'] }}."
