---
#####################################
# T-Pot - Prepare for Docker Engine #
#####################################

- name: Remove distribution based Docker packages and podman-docker (AlmaLinux, Debian, Fedora, Raspbian, RHEL, Rocky, Ubuntu)
  package:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
      - podman-docker
      - podman
    state: absent
    update_cache: yes
  when: ansible_distribution in ["AlmaLinux", "Debian", "Fedora", "Raspbian", "RedHat", "Rocky", "Ubuntu"]
  tags:
    - "AlmaLinux"
    - "Debian"
    - "Fedora"
    - "Raspbian"
    - "RedHat"
    - "Rocky"
    - "Ubuntu"

- name: Add folder for Docker Engine GPG key (Debian, Raspbian, Ubuntu)
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  when: ansible_distribution in ["Debian", "Raspbian", "Ubuntu"]
  tags:
    - "Debian"
    - "Raspbian"
    - "Ubuntu"

- name: Download Docker Engine GPG key (Debian, Raspbian, Ubuntu)
  get_url:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    dest: /etc/apt/keyrings/docker
    mode: '0755'
  when: ansible_distribution in ["Debian", "Raspbian", "Ubuntu"]
  tags:
    - "Debian"
    - "Raspbian"
    - "Ubuntu"

- name: Decrypt Docker Engine GPG key (Debian, Raspbian, Ubuntu)
  shell: gpg --dearmor /etc/apt/keyrings/docker
  args:
    creates: /etc/apt/keyrings/docker.gpg
  when: ansible_distribution in ["Debian", "Raspbian", "Ubuntu"]
  tags:
    - "Debian"
    - "Raspbian"
    - "Ubuntu"

- name: Add Docker Engine repository (Debian, Raspbian, Ubuntu)
  apt_repository:
    filename: docker
    repo: "deb [arch={{ ansible_architecture | replace('aarch64', 'arm64') | replace('x86_64', 'amd64') }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes
  when: ansible_distribution in ["Debian", "Raspbian", "Ubuntu"]
  tags:
    - "Debian"
    - "Raspbian"
    - "Ubuntu"

- name: Add Docker repository (Fedora)
  shell: |
    if [ "$(dnf repolist docker-ce-stable)" == "" ];
      then
        dnf -y config-manager addrepo --from-repofile=https://download.docker.com/linux/fedora/docker-ce.repo
    fi
  when: ansible_distribution in ["Fedora"]
  tags:
    - "Fedora"

- name: Add Docker repository (RHEL)
  shell: |
    if [ "$(dnf repolist docker-ce-stable)" == "" ];
      then
        dnf -y config-manager addrepo --from-repofile=https://download.docker.com/linux/rhel/docker-ce.repo
    fi
  when: ansible_distribution in ["RedHat"]
  tags:
    - "RedHat"

- name: Add Docker repository (AlmaLinux, Rocky)
  shell: |
    if [ "$(dnf repolist docker-ce-stable)" == "" ];
      then
        dnf -y config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    fi
  when: ansible_distribution in ["AlmaLinux", "Rocky"]
  tags:
    - "AlmaLinux"
    - "Rocky"
