---
#######################################################################
# T-Pot - Adjust group users, bashrc, clone / update T-Pot repository #
#######################################################################

# - name: Check for non-root user id (All)
#   debug:
#     msg: "Detected user: '{{ ansible_user_id }}'"
#   when: ansible_distribution in ["AlmaLinux", "Debian", "Fedora", "openSUSE Tumbleweed", "Raspbian", "RedHat", "Rocky", "Ubuntu"]
#   failed_when: ansible_user_id == "root"

- name: Add aliases
  blockinfile:
    path: ~/.bashrc
    block: |
      alias dps='{{ "grc --colour=on " if ansible_distribution != "RedHat" else "" }}docker ps -f status=running -f status=exited --format "table {{'{{'}}.Names{{'}}'}}\\t{{'{{'}}.Status{{'}}'}}\\t{{'{{'}}.Ports{{'}}'}}" | sort'
      alias dpsw='watch -c bash -ic dps'
      alias mi='micro'
      alias sudo='sudo '
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    insertafter: EOF
    state: present
  when: ansible_distribution in ["AlmaLinux", "Debian", "Fedora", "openSUSE Tumbleweed", "Raspbian", "RedHat", "Rocky", "Ubuntu"]
  tags:
    - "AlmaLinux"
    - "Debian"
    - "Fedora"
    - "openSUSE Tumbleweed"
    - "Raspbian"
    - "RedHat"
    - "Rocky"
    - "Ubuntu"

- name: Clone / Update T-Pot repository (All)
  git:
    repo: 'https://github.com/telekom-security/tpotce'
    dest: '/home/{{ ansible_user_id }}/tpotce/'
    version: master
    clone: yes
    update: no
  when: ansible_distribution in ["AlmaLinux", "Debian", "Fedora", "openSUSE Tumbleweed", "Raspbian", "RedHat", "Rocky", "Ubuntu"]

- name: Add current user to Docker, T-Pot group (All)
  become: true
  user:
    name: "{{ ansible_user_id }}"
    groups: 
      - docker
      - tpot
    append: yes
  when: ansible_distribution in ["AlmaLinux", "Debian", "Fedora", "openSUSE Tumbleweed", "Raspbian", "RedHat", "Rocky", "Ubuntu"]