---
########################################
# T-Pot - Install service and cron job #
########################################

- name: T-Pot - Install service
  hosts: all
  gather_facts: true
  become: false
  tags:
    - "AlmaLinux"
    - "Debian"
    - "Fedora"
    - "openSUSE Tumbleweed"
    - "Raspbian"
    - "RedHat"
    - "Rocky"
    - "Ubuntu"

  tasks:
    - name: Install systemd service (All)
      become: true
      ansible.builtin.template:
        src: '/home/{{ ansible_user_id }}/tpotce/installer/install/tpot.service'
        dest: '/etc/systemd/system/tpot.service'
        owner: root
        group: root
        mode: '0755'
      notify: Reload systemd and enable service
      when: ansible_distribution in ["AlmaLinux", "Debian", "Fedora", "openSUSE Tumbleweed", "Raspbian", "RedHat", "Rocky", "Ubuntu"]

  handlers:
    - name: Reload systemd and enable service
      become: true
      ansible.builtin.systemd:
        name: tpot.service
        daemon_reload: yes
        state: stopped
        enabled: yes
      when: ansible_distribution in ["AlmaLinux", "Debian", "Fedora", "openSUSE Tumbleweed", "Raspbian", "RedHat", "Rocky", "Ubuntu"]

- name: T-Pot - Setup a randomized daily reboot
  hosts: all
  gather_facts: true
  become: yes
  tags:
    - "AlmaLinux"
    - "Debian"
    - "Fedora"
    - "openSUSE Tumbleweed"
    - "Raspbian"
    - "RedHat"
    - "Rocky"
    - "Ubuntu"

  vars:
    random_minute: "{{ range(0, 60) | random }}"
    random_hour: "{{ range(0, 5) | random }}" # We want the reboot randomly happen at night

  tasks:
    - name: Setup a randomized daily reboot (All)
      cron:
        name: "T-Pot Daily Reboot"
        user: root
        minute: "{{ random_minute }}"
        hour: "{{ random_hour }}"
        job: "bash -c 'systemctl stop tpot.service && docker container prune -f; docker image prune -f; docker volume prune -f; /usr/sbin/shutdown -r +1 \"T-Pot Daily Reboot\"'"
        state: present
      when: ansible_distribution in ["AlmaLinux", "Debian", "Fedora", "openSUSE Tumbleweed", "Raspbian", "RedHat", "Rocky", "Ubuntu"]
