---
- name: Bootstrap Python
  ansible.builtin.include_tasks: bootstrap_python.yml

- name: Support Check
  ansible.builtin.include_tasks: support_check.yml

- name: Prep System
  ansible.builtin.include_tasks: prep_system.yml

- name: Prep for Docker
  ansible.builtin.include_tasks: prep_for_docker.ylm

- name: Install Docker
  ansible.builtin.include_tasks: install_docker.yml

- name: Config System
  ansible.builtin.include_tasks: config_system.yml

- name: Setup tpot
  ansible.builtin.include_tasks: setup_tpot.yml
